FROM golang:1.5.1

MAINTAINER Sakeven "sakeven.jiang@daocloud.io"

# 将源码复制到 $GOPATH/src/app，$GOPATH 为 /go
ADD . $GOPATH/src/app
# 下载安装依赖
RUN go get app
# 静态编译安装，最终可执行文件为 /go/bin/app
RUN CGO_ENABLED=0 go install -a app